<p>Los Docentes Pablo Noé Hernández Ulloa y Leonardo Hernández Peña,  asistieron a la  Ciudad de Hong Kong, donde fueron recibidos en la City University of Macau y participaron en la “Education and Career Expo Hong Kong 2018” con una ponencia sobre el modelo educativo de la Universidad Tecnológica de la Costa en el idioma inglés.
</p>
<p>Asimismo asistieron a conferencias y participaron con un stand con  universidades de cinco zonas: Australia, Canadá, China oriental, Europa, Estados Unidos y México, interactuaron con otros sistemas educativos, intercambiaron información y entablaron vínculos, con la finalidad de hacer contacto y poder firmar convenios de colaboración que coadyuven, a la movilidad internacional para la formación de profesores, fortalecer los procesos académicos, de investigación y métodos de enseñanza, mediante prácticas y experiencias que puedan adoptar en otras instituciones educativas, asimismo fomentar la diversidad cultural y  promover la  presencia de profesores visitantes extranjeros. 
</p>
<p>“Proyecto realizado con financiamiento de la Secretaría de Educación
Pública-Subsecretaría de Educación Superior-Dirección General de
Educación Superior Universitaria” en cumplimiento a lo establecido en el
Convenio celebrado con cada institución en el marco del Programa. PADES2017
</p>
