<p>Este viernes 16 de mayo, en las instalaciones de la <strong>Universidad Tecnológica de la Costa</strong>, se llevó a cabo un curso de capacitación para docentes  denominado: <strong>Operación de Centros de Evaluación</strong>, <strong>Aseguramiento de la Excelencia en la Atención</strong> y <strong>Servicio a Usuarios</strong>, impartido por la <strong>Maestra Mirella Maribel Pérez Dzul</strong>, <strong>Coordinadora de la Entidad de Certificación y Evaluación de Competencias de la Universidad Tecnológica Metropolitana de Mérida, Yucatán</strong>.</p>
<p>Este riguroso proceso se llevó acabo de manera exitosa, logrando con ello que  la <strong>Universidad Tecnológica de la Costa</strong> obtuviera el reconocimiento como Centro Evaluador de Competencias, basado en la Norma <strong>CONOCER</strong> (Consejo Nacional de Normalización y Certificación de Competencias Laborales) su misión es dar a México, a través del Sistema Nacional de Competencias de las personas, un instrumento más, impulsado desde el sector educativo, para fortalecer su competitividad económica, capacidad de crecimiento y progreso social para beneficio de todas y todos los mexicanos.</p>
<p>Se encuentra integrada por tres piezas clave: <strong>Comités de Gestión por Competencias (CGC)</strong>, <strong>Registros Nacionales</strong> y <strong>Estructura Nacional de Evaluación y Certificación de Competencias de Personas</strong>, siendo ya la UTC parte de dicha estructura.</p>
<p>Durante este proceso la <strong>Lic. Estrella Montero Jaime</strong>, Directora de la División de Ingeniería Económico Administrativa, el <strong>M.M. Eldy Martínez Flores</strong>, Jefe del Departamento de Prácticas y Estadías y la <strong>M.M. Alejandra Quezada Ruíz</strong>, Docente de la Institución, fueron evaluados de manera satisfactoria logrando la certificación en los estándares:
<em>Evaluación de la Competencia de Candidatos con base en Estándares de Competencias y  Ventas Consultivas.</em>
Derivado de lo anterior, la Universidad cuenta con la acreditación  para   capacitar y evaluar, con fines de certificación, las competencias de las personas que desarrollen funciones relacionadas con ventas consultivas, en situaciones  donde el vendedor identifica necesidades específicas de sus clientes.</p>
<p>Con estas certificaciones se abre camino rumbo a nuevos Estándares de Competencia inscritos en el <strong>Registro Nacional de Estándares de Competencias</strong>.
En este sentido, el Rector de la Universidad Tecnológica de la Costa, Ing. Manuel Quintero Borrego declaró: <em>“Estamos tomando el rumbo correcto, perfilando a nuestra Institución como referente de calidad educativa y brindando servicios al sector productivo, fortaleciendo los lazos de vinculación.</em></p>
<p><em>Me siento orgulloso de nuestro cuerpo docente, que día con día demuestra identidad y compromiso institucional, felicito de manera especial a la Lic. Estrella Montero Jaime M.M. , Eldy Martínez Flores y la Maestra Alejandra Quezada Ruíz por su certificación, gracias por llenarnos de grandes satisfacciones a todos los que somos parte de esta importante Institución Educativa”</em>, concluyó.</p>
<p class="reduced">Es así como una vez más la Universidad Tecnológica de la Costa cumple con su misión que consiste en ser una Institución formadora de profesionistas en las áreas de agronegocios y servicios, capaces de transformar el entorno, impulsando el desarrollo económico, social y cultural en la zona de influencia.
</p>