<p><em>“Gracias al compromiso de apoyo y colaboración del Gobernador del Estado Roberto Sandoval Castañeda, Nayarit es hoy  un Estado de excelencia, una tierra de grandes oportunidades y  cuenta con la  Universidad Tecnológica de la Costa, Institución educativa que fortalecerá el desarrollo agropecuario de la Zona Norte.”</em></p>
<p>Así lo manifestó en <strong>Ingeniero Manuel Quintero Borrego</strong>, Rector de la Universidad Tecnológica de la Costa este viernes 11 de julio en el <strong>Acto de Clausura de la Cuarta Generación de Ingeniería 2012-2014</strong>,  de la cual egresaron 101 jóvenes de las Ingenierías en <strong>Desarrollo e Innovación Empresarial, Procesos Alimentarios, Procesos Biotecnológicos y Tecnologías de la Información y Comunicación</strong>.</p>
<p>Quintero Borrego Agregó: En nuestra Institución seguimos una directriz encaminada a la Unidad, porque Unidos, somos más fuertes, trabajamos en equipo entre alumnos, padres de familia, docentes y personal administrativo, para ofrecer al sector productivo egresados con calidad UTC.</p>
<p>Los felicito por este logro, gracias por confiar en nuestra Institución, tengan presente que no se están llevando solo una certificación, se están llevando algo más trascendente e insustituible que es el conocimiento y en esta era, ese es el recurso más valioso, concluyó.</p>
<p>La mesa de honor estuvo integrada por el Rector de la <strong>Universidad Tecnológica de la Costa, L.Q. Ignacio Manuel Quintero Borrego</strong>, acompañado del Cuerpo Directivo.
Se entregaron reconocimientos especiales por Ingenierías a los alumnos destacados de esta generación, quedando de la siguiente manera:</p>
<p>Los mejores proyectos de estadía fueron para: Meza Huerta Víctor Ociel de IDIE, por el Proyecto: Planeación, Organización e Implementación del Área de Recursos Humanos en la Empresa Satinet de México S. de R.L.  de C.V., Santillán Castañeda Adilene (IPA),  Estudio de la Interacción de Biopolímeros (proteína-goma arábiga) por Espectroscopía de Infrarrojo, Ortega Sánchez Ezequiel (IPB),  Monitoreo de Adultos de Lepidópteros Mediante Trampas con Atrayente Alimenticio y Miramontes Olavarría Eduardo (ITIC), por el proyecto: Análisis para el Sistema Integral de la Caja Popular Río Presidio y Desarrollo e Implementación del Módulo del Sistema de Entrada y Salida del Personal Trabajador Mediante Lector de Huella Digital.
Los mejores promedios por generación quedaron de la siguiente manera: Carrillo Sandoval Jahely Sayani (IDIE), Salazar Pérez Carmen (IPA),  Raygoza Lucatero Sergio (IPB) y Ramírez Sánchez Ramón Alejandro (ITIC).</p>
<p>Las palabras de agradecimiento y despedida estuvieron a cargo de la joven <strong>Fátima Paredes Bañuelos</strong>, egresada de la Ingeniería Tecnologías de la Información y Comunicación, mientras que el encargado de tomar protesta a los nuevos Ingenieros fue el  <strong>Secretario Académico y de calidad educativa Ing. Edgar Santiago Hernández Barragán</strong>, quien exhortó a los jóvenes egresados a demostrar los conocimientos adquiridos, poniendo en alto el nombre de la Institución.</p>
<p class="reduced">Es así como esta Institución educativa  contribuye al desarrollo de la Zona Norte, del Estado y del País, entregando a la sociedad profesionistas con alto grado de competitividad, capaces de afrontar los retos que el mundo actual les presenta pero sobre todo con el sello de garantía de la Universidad Tecnológica de la Costa.</p>