<p>Con el firme propósito de mantener actualizada la planta docente que integra la Universidad Tecnológica de la Costa, en este periodo correspondiente al segundo año de administración del Rector de la Institución, Ing. Ignacio Manuel Quintero Borrego, se mantuvo en constante capacitación a los profesores de asignatura y de tiempo completo.</p>
<p>Previo al inicio del ciclo escolar 2013, se impartió una serie de cursos de capacitación que les permitieron enriquecer la calidad educativa que imparten al interior de las aulas.
</p>
<p>Posteriormente se impartieron los siguientes cursos de capacitación: Principios Básicos del Comercio Internacional, impartido por el  <strong>Dr. José Gerardo Tajonar Castro</strong>, del <strong>Centro Facilitador Global de Comercio Trade Point de México A.C.</strong> con el objetivo de homologar conceptos en materia de comercio y negocios internacionales, enriquecer los conocimientos de las principales temáticas que abordan las operaciones de comercio exterior, proporcionar los elementos necesarios para la elaboración y desarrollo de un plan de negocios de exportación y brindar herramientas estratégicas para alcanzar negociaciones y contratos internacionales exitosos.</p>
<p><em>“Branding Estratégico”</em>,  impartido por el <strong>M.C. Víctor Manuel López Guzmán</strong>, de Grupo Exporta, el objetivo fue  aumentar el nivel de conocimientos en temas relativos al Branding Estratégico, además de unificar sus visiones, criterios y competencias en  proyectos de investigación.</p>
<p><em>“Formulación y Evaluación de Proyectos Nivel 1”</em>, impartido por el <strong>Ing. Gonzalo  Barbosa García</strong> del <strong>Centro de Desarrollo Tecnológico de FIRA (CDT) Salvador Lira López de la Ciudad de Morelia</strong>, Michoacán, el objetivo de este curso fue el adquirir los conocimientos necesarios para la  formulación  y evaluación de un proyecto productivo y a su vez decidir sobre la rentabilidad de estos,   así como identificar factores críticos que les permitan desarrollar una estrategia de mejora, para minimizar los riesgos.</p>
<p>Agregar que en las convocatorias 2013 emitidas por <strong>PROMEP (Programa de Mejoramiento al Profesorado)</strong>, se suman 5 docentes con reconocimiento a perfil deseable, además se obtiene una renovación y un complemento al monto obtenido en la convocatoria de 2011 derivado del aumento de su grado académico.</p>
<p>Derivado de tales actividades, este año se logró obtener el <em>“Apoyo de Implementos Básicos para el Trabajo Académico de PTC Reconocidos con el Perfil Deseable”</em> por la cantidad de $130,000.00, recurso que podrá ser aplicado para la  adecuación, remodelación y  adquisición de mobiliario para cubículos, así como adquisición de equipo personal de cómputo, periféricos de cómputo o electrónicos, acervo bibliográfico o informático especializado y  equipo para experimentación.</p>
<p class="reduced">Es una realidad que en este segundo año de administración del Ing. Manuel Quintero Borrego,  con esta serie de cursos de capacitación a  docentes, la Universidad Tecnológica de la Costa, coadyuva  en la formación de los futuros profesionistas y sobre todo fortalece su espíritu emprendedor.</p>
